#!/bin/sh

cwd="$(pwd)"

ln -s $cwd/aliases $HOME/.aliases
ln -s $cwd/tmux.conf $HOME/.tmux.conf
ln -s $cwd/vimrc $HOME/.vimrc
ln -s $cwd/zshrc $HOME/.zshrc
ln -s $cwd/zsh-themes $HOME/.zsh-themes

mkdir -p $HOME/.config/i3
ln -s $cwd/i3config $HOME/.config/i3/config
